# Replace <password> with your actual password
spring.data.mongodb.uri=mongodb+srv://anuj:prajapati@cluster0.fnbethv.mongodb.net/farm_marketplace?retryWrites=true&w=majority&appName=Cluster0

server.address=0.0.0.0